#################################################################
#                                                               #
#         NetApp ONTAP Volume Creation with Variable Loop       #
#                       Date: 10/30/2019                        #
#                                                               #
#################################################################

---
- name: Volume Creation with Variable Loop
  hosts: localhost
  tasks:
   - name: Create NFS Volumes
     na_ontap_volume:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name: '{{ name }}_0{{ item }}'
       is_infinite: False
       aggregate_name: '{{ node_a_data_aggr_name }}'
       size: '{{ size }}'
       size_unit: gb
       volume_security_style: unix
       space_guarantee: none
       policy: default
       junction_path: '/{{ name }}_0{{ item }}'
       percent_snapshot_space: '0'
       vserver: '{{ svm_name }}'
       is_online: yes
     loop: '{{ range(1, num_of_vols + 1)|list }}'
     loop_control:
       index_var: loop_idx
