#################################################################
#                                                               #
#            Mounting NFS Datastores with Variable Loop         #
#                                                               #
#################################################################
#                                                               #
#     This code is released as Creative Commons BY-SA. This     #
#   playbook was created for the Insight Tech Tuesday webinar   #
#   on 11/5/2019. The configurations in this playbook do not    #
#    represent Insights reccomended practices. This playbook    #
#     was created simply to demonstrate the capabilities of     #
#     Ansible and Ansible Tower. To request support of this     #
#    playbook, or for further information on how Insight can    #
#      assist with your automation needs, please reach out      #
#                  to your account executive.                   #
#                                                               #
#################################################################

---
- name: NFS SVM Creation
  hosts: localhost
  tasks:
   - name: Create SVM
     na_ontap_svm:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name: '{{ svm_name }}'
       language: en.UTF-8
       allowed_protocols: nfs
       root_volume: '{{ svm_name }}_root'
       root_volume_aggregate: '{{ node_a_data_aggr_name }}'
       root_volume_security_style: ntfs
   - name: Start NFS Service
     na_ontap_nfs:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       service_state: started
       vserver: '{{ svm_name }}'
       nfsv3: enabled
       nfsv4: disabled
       nfsv41: disabled
       vstorage_state: disabled
   - name: Create NFS Node A Interface
     na_ontap_interface:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       vserver: '{{ svm_name }}'
       interface_name: '{{ svm_name }}_NFS_1'
       home_port: 'a0a-{{ nfs_vlan }}'
       home_node: '{{ node_a }}'
       role: data
       protocols: nfs
       admin_status: up
       force_subnet_association: true
       address: '{{ nfs_a_ip }}'
       netmask: 255.255.255.0
   - name: Create NFS Node B Interface
     na_ontap_interface:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       vserver: '{{ svm_name }}'
       interface_name: '{{ svm_name }}_NFS_2'
       home_port: 'a0a-{{ nfs_vlan }}'
       home_node: '{{ node_b }}'
       role: data
       protocols: nfs
       admin_status: up
       force_subnet_association: true
       address: '{{ nfs_b_ip }}'
       netmask: 255.255.255.0
   - name: Create NFS Export Policy
     na_ontap_export_policy:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name: '{{ export_pol_name }}'
       vserver: '{{ svm_name }}'
   - name: Edit default NFS Export Policy Rule
     na_ontap_export_policy_rule:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name:  default
       vserver: '{{ svm_name }}'
       client_match: '{{ export_client_match }}'
       ro_rule: any
       rw_rule: any
       super_user_security: any
       allow_suid: true
   - name: Create NFS Volume 1
     na_ontap_volume:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name: '{{ svm_name }}_NFS_Vol01'
       is_infinite: False
       aggregate_name: '{{ node_a_data_aggr_name }}'
       size: '{{ nfs_vol_1_size }}'
       size_unit: gb
       volume_security_style: unix
       space_guarantee: none
       policy: default
       junction_path: '/{{ svm_name }}_NFS_Vol01'
       percent_snapshot_space: '0'
       vserver: '{{ svm_name }}'
       is_online: yes
   - name: Create NFS Volume 2
     na_ontap_volume:
       state: present
       hostname: '{{ netapp_hostname }}'
       username: '{{ netapp_username }}'
       password: '{{ netapp_password }}'
       name: '{{ svm_name }}_NFS_Vol02'
       is_infinite: False
       aggregate_name: '{{ node_b_data_aggr_name }}'
       size: '{{ nfs_vol_2_size }}'
       size_unit: gb
       volume_security_style: unix
       space_guarantee: none
       policy: default
       junction_path: '/{{ svm_name }}_NFS_Vol02'
       percent_snapshot_space: '0'
       vserver: '{{ svm_name }}'
       is_online: yes
