#################################################################
#                                                               #
#             Create a Virtual Machine from a Template          #
#                                                               #
#################################################################
#                                                               #
#     This code is released as Creative Commons BY-SA. This     #
#   playbook was created for the Insight Tech Tuesday webinar   #
#   on 11/5/2019. The configurations in this playbook do not    #
#    represent Insights reccomended practices. This playbook    #
#     was created simply to demonstrate the capabilities of     #
#     Ansible and Ansible Tower. To request support of this     #
#    playbook, or for further information on how Insight can    #
#      assist with your automation needs, please reach out      #
#                  to your account executive.                   #
#                                                               #
#################################################################

---
- name: Create a Virtual Machine from a Template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a Virtual Machine from a Template
    vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ vcenter_cluster_name }}'
      validate_certs: no
      folder: /Ansible_Demo
      name: '{{ vm_name }}'
      state: poweredoff
      template: mssql-o
      datastore: '{{ datastore_name }}'
    delegate_to: localhost
    register: deploy
