#################################################################
#                                                               #
#            Check Datastore to Confirm Available Space         #
#                       Date: 10/30/2019                        #
#                                                               #
#################################################################
#                                                               #
#     This code is released as Creative Commons BY-SA. This     #
#   playbook was created for the Insight Tech Tuesday webinar   #
#   on 11/5/2019. The configurations in this playbook do not    #
#    represent Insights reccomended practices. This playbook    #
#     was created simply to demonstrate the capabilities of     #
#     Ansible and Ansible Tower. To request support of this     #
#    playbook, or for further information on how Insight can    #
#      assist with your automation needs, please reach out      #
#                  to your account executive.                   #
#                                                               #
#################################################################

---
- name: Check Datastore Space Based on Number of VMs Requested
  hosts: all
  connection: local
  gather_facts: no
  vars:
    requested_space: '{{ (number_of_vms * 100)|int }}'
  tasks:
  - name: Gather Facts from Datacenter about a Specific Datastore
    vmware_datastore_facts:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      name: '{{ datastore_name }}'
      validate_certs: no
    register: facts
  - name: Compare Requested Space to Available Space
    debug:
      msg: 'Comparing requested space: {{ requested_space }}GB to available space: {{ (facts.datastores[0].freeSpace/1024|pow(3))|round|int }}GB'
    failed_when: requested_space|int > (facts.datastores[0].freeSpace/1024|pow(3))|round|int
