#################################################################
#                                                               #
#                      Rescan NFS Datastore                     #
#                                                               #
#################################################################
#                                                               #
#     This code is released as Creative Commons BY-SA. This     #
#   playbook was created for the Insight Tech Tuesday webinar   #
#   on 11/5/2019. The configurations in this playbook do not    #
#    represent Insights reccomended practices. This playbook    #
#     was created simply to demonstrate the capabilities of     #
#     Ansible and Ansible Tower. To request support of this     #
#    playbook, or for further information on how Insight can    #
#      assist with your automation needs, please reach out      #
#                  to your account executive.                   #
#                                                               #
#################################################################

---
- name: Rescan NFS Datastore
  hosts: all
  connection: local
  gather_facts: no
  tasks:
#  - name: Start SSH Service Setting for all ESXi Hosts in given Cluster
#    vmware_host_service_manager:
#      hostname: '{{ vcenter_hostname }}'
#      username: '{{ vcenter_username }}'
#      password: '{{ vcenter_password }}'
#      cluster_name: '{{ vcenter_cluster_name }}'
#      validate_certs: no
#      service_name: sshd
#      state: start
#    delegate_to: localhost
  - name: Rescan NFS Datastore
    cli_command:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      command: vmkfstools -V
    delegate_to: localhost
#  - name: Start SSH Service Setting for all ESXi Hosts in given Cluster
#    vmware_host_service_manager:
#      hostname: '{{ vcenter_hostname }}'
#      username: '{{ vcenter_username }}'
#      password: '{{ vcenter_password }}'
#      cluster_name: '{{ vcenter_cluster_name }}'
#      validate_certs: no
#      service_name: sshd
#      state: stop
#    delegate_to: localhost
